### ISSUE TITLE
Upcoming Guns

### ISSUE THREAD

**Issue by CasualNoLifer** [Pinelog-Studios/AdditionalGuns#62]
Public list of guns that will appear in future updates. These will not all necessarily come out in the same update. 
(Checked means that model/model tweaks have been finished by me and are awaiting gun data creation/custom sounds, also by me.)

Contributed models are touched up to be more consistent or work well and the textures are changed to be white/grayscale in order to be compatible with dyeing. If you specifically do not want your gun to have attachments or dye compatibility, please let me know.

If your model is on this list and you do not want it to be, please message me on Discord at **CasualNoLifer#1313**. If you are a part of Mr. Pineapple's Discord server, you can also message me on there. These methods of contact can also be used if you are interested in contributing your gun model, textures or sounds.

**All models shown here are subject to changes. Check back here occasionally for updates to weapons you are interested in. :)**

- [x] Golden Eagle (Hobbeswyn, CasualNoLifer textures)
![golden_eagle](https://user-images.githubusercontent.com/64159930/179444335-7217e10c-a3dd-4da4-a802-3132a395f138.png)

- [x] DP-27 (Hobbeswyn, Additional Guns Textures)
![dp27](https://user-images.githubusercontent.com/64159930/179624040-a1ce7683-175b-4fb3-b212-7ce3f9029b7c.png)

- [x] Maxim-9 (Hobbeswyn, Additional Guns Textures)
![maxim9](https://user-images.githubusercontent.com/64159930/179443394-e60edfc8-0699-4162-8900-3e15af3f031c.png)

- [x] TAR-21 (Hobbeswyn, Additional Guns Textures)
![tar_21](https://user-images.githubusercontent.com/64159930/179443377-caba3eef-b326-4645-ac5b-d664d593c7e6.png)

- [x] "Holo-Tek Sight" -- TAR-21 Sight (Hobbeswyn)
**Sight picture is theoretical/conceptual**
![tar_212](https://user-images.githubusercontent.com/64159930/179443381-dff63ead-5379-4f46-8687-061c45163c0d.png)

- [x] MP5A4 (Hobbeswyn, Additional Guns Textures)
![mp5a4](https://user-images.githubusercontent.com/64159930/179624957-0f6a8f0d-56c7-4fa9-b608-c4c97df31537.png)

- [x] Drakon Sniper Rifle (Hobbeswyn, Additional Guns Textures)
**From the Call of Duty franchise.**
![drakon](https://user-images.githubusercontent.com/64159930/179617855-6d5a0486-78be-4302-ac0e-f31c7903b8f0.png)

- [x] M41A Pulse Rifle (Hobbeswyn, Additional Guns Textures)
**From the Alien franchise.**
![m41apulserifle](https://user-images.githubusercontent.com/64159930/179611322-27a1a0ff-69b5-4e1c-8608-b539edb63fe6.png)

- [x] Auto 9 (Hobbeswyn, Additional Guns Textures)
**From the Robocop franchise.**
![auto9](https://user-images.githubusercontent.com/64159930/179628652-6aa524d7-5f0a-4063-83cc-ea89e62eed8e.png)

- [x] Barrett M95 (Hobbeswyn, Additional Guns Textures)
![barrett](https://user-images.githubusercontent.com/64159930/179628669-ea0518ff-86a8-4672-9561-8a161bd66e31.png)

- [x] Barrett M95 Scope (Hobbeswyn)
**Potential to be scrapped due to scope not being hollow**
![barrettscope](https://user-images.githubusercontent.com/64159930/179628679-20985ebc-2cd5-4a5c-8885-a355d43f5f6f.png)

- [x] AA-12 (Hobbeswyn)
![aa12](https://user-images.githubusercontent.com/64159930/179632414-8741102a-e22f-49d4-a05c-e5f46eb97661.png)

- [x] M249 (Hobbeswyn, Additional Guns Textures, CasualNoLifer Custom M4 Extended Magazine)
![m249](https://user-images.githubusercontent.com/64159930/179637181-4dca2966-55f9-4421-88b5-fb737416eabc.png)

- [x] KSG-12 (CasualNoLifer)
![ksg12](https://user-images.githubusercontent.com/64159930/179441878-984db3a1-914c-4f5c-a49d-0489f4cc9e98.png)

- [ ] P90 (CasualNoLifer)
**Note: Dedicated to Autovw. :)**

- [x] UMP-45 (Mercuriosity and CasualNoLifer)
**Note: This gun was originally scrapped due to the model facing the wrong axis but has been considered again due to the issue being fixed.**
![ump45](https://user-images.githubusercontent.com/64159930/180612755-539859a0-1cad-4bdb-8831-f564e5812ebc.png)

- [x] MP7 (Mercuriosity and CasualNoLifer)
**Note: There is a difference between the MP7 and MP7A2. The MP7 will have an identical model to the MP7A2 but will have an extended magazine, stock and barrel.**
![mp7](https://user-images.githubusercontent.com/64159930/180612727-57b74e13-7565-410c-aad9-5c4cfa87a9d2.png)

- [ ] Unica 6 (CasualNoLifer)

- [ ] HK416 (CasualNoLifer)

- [ ] PSL (CasualNoLifer)

- [ ] TEC-9 (CasualNoLifer)

- [ ] MP5K (CasualNoLifer)

- [ ] NEOSTEAD (CasualNoLifer)

- [ ] FMG-9 (CasualNoLifer)

- [x] Kolibri (Iggosha)
![kolibri-try2](https://user-images.githubusercontent.com/64159930/179441820-447c057e-5a6e-4ba7-9873-885d3bbfb5e7.png)

- [x] PKM (Igggosha)
![pkm](https://user-images.githubusercontent.com/64159930/180612762-b05f2ceb-4bc4-4e4f-9988-7e68146f338c.png)

- [x] Python (Lieutenant Howitzer)
![colt_python](https://user-images.githubusercontent.com/64159930/179441651-bea032e8-e115-44a5-8b53-21a96d0073c0.png)

- [ ] Sawn-Off (Lieutenant Howitzer)

- [ ] Model 555 (Lieutenant Howitzer)

- [ ] Uplander DB (Lieutenant Howitzer)

- [x] M1911A1 (Lieutenant Howitzer)
![m1911a1_v1](https://user-images.githubusercontent.com/64159930/180613039-099890c8-46ed-4c8c-9534-e26d602f4ece.png)

- [ ] Malorian (Joel McCassidy)

- [x] SCAR-H (WitherFlint343 and CasualNoLifer)
![scarh](https://user-images.githubusercontent.com/64159930/179441861-b763d1f6-f93d-4034-9224-9087078d9820.png)

- [x] DSR-50 (WitherFlint343)
![dsr-50](https://user-images.githubusercontent.com/64159930/179441846-960753b5-990a-48fc-9d12-fafcb67ae1ad.png)

- [ ] DSR-50 Scope (WitherFlint343)

- [x] CZ-75 (WitherFlint343)
![cz-75](https://user-images.githubusercontent.com/64159930/179442065-71500888-9148-432f-9206-9ede1efd4d6f.png)

- [x] M92 (WitherFlint343)
![b92](https://user-images.githubusercontent.com/64159930/179442736-d12b0706-362f-482f-a593-70e97c32c7e6.png)

- [x] GM-60 (WitherFlint343)
![GM60](https://user-images.githubusercontent.com/64159930/179443486-5f1805a0-0371-4384-88ab-a80b630a9c1b.png)

- [x] GALIL-ACE SBR (WitherFlint343)
![galilacesbr](https://user-images.githubusercontent.com/64159930/179632469-9efc5bbe-7708-437b-894d-f381ab957cfc.png)

- [ ] MP5SD (WitherFlint343)

**Comment by CodeGenStudio** [comment]
If I may add a few (*cough*) more guns as suggestions, which hopefully anyone would be willing to take on and implement:

1. SV-98 [image](https://adelbridge.com/wp-content/uploads/2021/11/Izhmash-SV-98-7.62-scaled.jpg)
2. AK-47 [image](https://upload.wikimedia.org/wikipedia/commons/6/65/AK-47_type_II_noBG.png)
3. TEC9 [image](https://static.wikia.nocookie.net/battlefield/images/e/e8/TEC-9.jpg/revision/latest?cb=20150124220927)
4. AN-94 [image](https://modernfirearms.net/wp-content/uploads/2010/10/an94-r.jpg)
5. MICROUZI [image](https://cdn11.bigcommerce.com/s-wkf3yob290/images/stencil/1280x1280/products/1187/1340/IMG_0690__70424.1583439809.png?c=2)
6. AWP [image](https://ae01.alicdn.com/kf/U4a555a012c5f4f009257e129104a9f07D/AWM-awp.jpg_Q90.jpg_.webp)
7. SIG556 [image](https://sigsauerarmory.com/wp-content/uploads/2021/08/SS4.jpg)
8. GALIL [image](https://iwi.net/wp-content/uploads/2021/08/ACE_22_IWI_3687.jpg)
9. DAEWOOK2 [image](http://www.military-today.com/firearms/k2.jpg)
10. MP5 [image](https://www.heckler-koch.com/typo3temp/_processed_/csm_MP5A3_re_6691b1ed48.png)
11. MP5SD [image](https://hk-usa.com/wp-content/uploads/1-MP5SDA2-RIGHT-JULY-20161.jpg)
12. MP7 [image](https://upload.wikimedia.org/wikipedia/commons/4/44/Heckler_%26_Koch_MP7A1.png)
13. NEGEV [image](https://www.redrock.ch/images/product_images/original_images/IWI_Negev_7_ULMG.png)
14. FAMAS-F1 [image](https://modernfirearms.net/wp-content/uploads/2010/10/famasf11.jpg)
15. QBZ95 [image](https://upload.wikimedia.org/wikipedia/commons/a/a7/QBZ95_automatic_rifle_mod_noBG.png)
16. R8 REVOLVER [image](https://imageio.forbes.com/blogs-images/insertcoin/files/2015/12/revolver.jpg?format=jpg&width=1200)
17. P2000 [image](https://palmettostatearmory.com/media/catalog/product/3/1/31535.jpg)
18. NEOSTEAD [image](https://static.wikia.nocookie.net/guns/images/8/8d/Neostead.jpg/revision/latest?cb=20161125005500)
19. FMG9 [image](https://upload.wikimedia.org/wikipedia/commons/6/67/Magpul_FMG9.png)
20. M60 [image](https://cdn.rockislandauction.com/dev_cdn/82/1566.jpg)
21. MP9 [image](https://upload.wikimedia.org/wikipedia/commons/0/09/MP9.png)
22. VITYAZ [image](https://static.wikia.nocookie.net/guns/images/f/f6/VityazSN.jpg/revision/latest?cb=20190416123535)

**Comment by CasualNoLifer** [comment]
> If I may add a few (_cough_) more guns as suggestions, which hopefully anyone would be willing to take on and implement:

Hi, thanks for your suggestion! Couple comments on those:
- SV-98 is too similar to the AWM/AWP to be worth making
- There are already 9 AK platform guns in this mod lol
- Tec-9 is a good idea and is on my list of ideas
- AN-94 is one of my favorite assault rifles and is definitely one I'd want in
- Micro UZI is a good idea but they're usually dual wielded which is not something we can do
- There is already an AWM and 2-3 possible usable AWP models that may be implemented
- SIG556 is kinda meh 
- We have a GALIL ACE sitting in the dark corner somewhere. Might use it here. ;)
- Daewook is meh
- There is an MP5A4 and MP5SD (not added on this list) upcoming. A normal MP5 is next to impossible to do with the Minecraft angle limitations
- There is already an MP7A2 but a normal MP7 would be interesting
- There is an M249 and ares shrike possibility. Negev is similar but not identical to the former.
- We have the most beautiful model ever that is a Famas F1, but we are using it for another project
- QBZ-95 is a very good idea and one I'd like to see
- R8 isn't really unique as far as revolvers go so probably not since Unica 6 and Python are planned to join Magnum in the revolver family
- P2000 looks too similar to the P250 and other pistols
- Neostead - yes
- FM9 - yes
- M60 - yes
- MP9 - no
- VITYAZ - maybe

**Comment by CodeGenStudio** [comment]
Thanks a lot to you for looking into my list of suggestions!

> We have the most beautiful model ever that is a Famas F1, but we are using it for another project

So you have a model for it, but or a different gun? Or for a different mod itself?

> There is an M249 and ares shrike possibility. Negev is similar but not identical to the former.

> P2000 looks too similar to the P250 and other pistols

Lol, I was thinking the exact same when adding but I'm lazy to remove them from the list. xd

> There are already 9 AK platform guns in this mod lol

True... but I felt we need a spot for the OG, lmao

**Comment by CasualNoLifer** [comment]
> Thanks a lot to you for looking into my list of suggestions!
> 
> > We have the most beautiful model ever that is a Famas F1, but we are using it for another project
> 
> So you have a model for it, but or a different gun? Or for a different mod itself?
> 
> > There is an M249 and ares shrike possibility. Negev is similar but not identical to the former.
> 
> > P2000 looks too similar to the P250 and other pistols
> 
> I was thinking the exact same when adding but I'm lazy to remove them from the list. xd
> 
> > There are already 9 AK platform guns in this mod lol
> 
> True... but I felt we need a spot for the OG, lmao

We have a model for the FAMAS that is very nice. This is one of the addon projects that a few of the main contributors for this mod are working on. We have another one called Secret Armory that will feature the FAMAS as the "poster child" weapon, so it won't be featured in this specific mod.

We're working on the M249 at the moment. It's going to use an M4 magazine so that people don't complain about the bullets used in the belt-feed system being inconsistent with our ammo types.

In that case, I may work on an AK but make it a golden AK similar to the Golden Eagle. There is already a desert eagle in the mod but that one is just special. :P
