### ISSUE TITLE
0.8.0 Development

### ISSUE THREAD

**Issue by CasualNoLifer** [Pinelog-Studios/AdditionalGuns#72]
This is an overview of what **we would like** to do in the 0.8.0 update of Additional Guns

**Model Improvements**
- [ ] Banshee model improvements
- [x] USP model improvements
- [ ] OTs-03 model tweaks
- [ ] Desert Eagle model tweaks
- [ ] AK-105 model tweaks
- [ ] M1911 model tweaks
- [ ] Muzzle Break model improvements
- [ ] MAT-49 model improvements
- [ ] Mac-10 iron sight tweaks
- [ ] Glock 18 iron sight improvements
- [ ] G11 iron sight improvements and slight barrel extension
- [ ] AKS-74U iron sight improvements
- [x] 9A-91 iron sight improvements, model tweaks, UV tweaks and texture tweaks
- [ ] Raven's Claw iron sight improvements
- [ ] Vector iron sight improvements
- [ ] Vector first person model edits, made two-handed and given an underbarrel attachment slot
- [x] AUG iron sight and grip model improvements
- [ ] F2000 iron sight improvements
- [ ] Kobra Scope scaled down slightly
- [ ] Zerkalo Scope repositioned and made dyeable
- [ ] All AKs will be distinguishable by color and texture and/or model
- [ ] MP7A2 dye zones tweaked
- [ ] USP, Glock 18, Deagle, and P250 receive dyeable lights on their respective iron sights

**Renames**
- [ ] M4A1-S renamed to M4A1
- [ ] FN2000 renamed to F2000
- [ ] AK-74M renamed to AK-74 Custom, or have one designated term for "modular" rather than some using "Custom" and others using "m"
- [ ] OTs-03 renamed to "Dragunov SVU," "Dragunov," or "SVU" as the current name is lesser known. This change would aim to make the gun more popular

**Stat Tweaks**
- [x] USP universal buff
- [ ] P250 nerf
- [ ] Magnum nerf and recoil rework
- [ ] M1911 nerf
- [ ] Vector slight buff
- [ ] M4A1, M4A4 and M16A2 buff
- [ ] AK-12 buff
- [ ] F2000 nerf
- [x] AUG nerf
- [ ] Val recoil rework
- [ ] Vintorez recoil rework
- [ ] 9A-91 recoil rework
- [ ] AK-15 rework
- [ ] Damage falloff introduced and all guns receive a bullet life/size/speed rework
          - "Submachine Gun" stat category
          - "Machine Pistol" stat category
          - "Small Pistol" stat category
          - "Handgun" stat category
          - "Handcannon" stat category
          - "Revolver" stat category
          - "Shotgun" stat category
          - "Assault Rifle" stat category
          - "Heavy Assault Rifle" stat category
          - "Rifle" stat category
          - "Sniper Rifle" stat category
          - "Heavy Sniper Rifle" stat category

**Technical Changes**
- [ ] Several guns with built-in attachments are edited to not have those attachments and the removed attachments become their own individual item. This will include:
          - AK-74m and AKM Custom's stocks will become "Advanced Stock"
          - M4A4 and M4A1's stocks will become "Light Military Stock"
          - M16A2's stock will become "Full Stock"
          - AK-12 and AK-15's stocks will become "Traditional Stock"
          - Val's integrated stock will become "Val Stock"
          - Val and Vintorez' barrels will become "Integrally Suppressed Barrel" (intsup_barrel)
          - 9A-91's suppressor will be removed and will use the same barrel attachment as the Val and Vintorez
- [ ] Unique or different sight pictures for the sights in this mod
- [x] USP ADS location tweaked
- [x] Deagle ADS location tweaked
- [x] Mac-10 ADS location tweaked
- [x] AWM ADS location tweaked
- [x] Magnum will no longer have scope attachment compatibility due to issues relating to placement, size and functionality of scopes
- [ ] Desert Eagle, Ace of Spades, P250, and Raven's Claw will no longer have muzzle attachment compatibility (does not have fluted barrel) -- stats will remain the same because of introduction of stocks to pistols
- [ ] 9A91, Val, Vintorez, AK-74m, AKM Custom, AK-104, AKS-74U, AK-12, AK-15, Vector, Banshee and M4A4 will have **all attachment slots unlocked**
- [ ] Schwarzlose will finally have a scope attachment slot
- [ ] OTs-03 will have an underbarrel slot
- [ ] Special Ammo and Special Ammo Casing inventory model location centered like the other ammo types
- [ ] Long Ammo and Long Ammo Casing inventory model resized so as not to clip through inventory slots
- [ ] Angled Grip inventory model size decreased to be more consistent with other attachments

**New Guns**
- [ ] PKM (Igggosha)
- [ ] Kolibri (Igggosha) - **Will not have attachments**
- [ ] M1911A1 (Lieutenant Howitzer)
- [ ] Python (Lieutenant Howitzer)
- [ ] SCAR-H (WitherFlint343)
- [ ] Galil ACE (WitherFlint343)
- [ ] GM-60 (WitherFlint343) - **Will not have attachments**
- [ ] KSG-12 (CasualNoLifer)
- [ ] MP7 (Mercuriosity and CasualNoLifer)
- [ ] Glock 19 (VIKTORWOOD and CasualNoLifer)
- [ ] UMP-45 (Mercuriosity and CasualNoLifer)

**New Attachments**
- [ ] Tactical Grip
- [ ] Minimal Angled Grip
- [ ] Compensator
- [ ] Special Silencer
- [ ] Sniper Scope (Super Long Scope)
- [ ] Minimal Stock (s_basic_stock)
- [ ] Recoil Reduction (Invisible Stock) **(A stock that is not visible but still gives the same stat changes as a stock: for cosmetic purposes -- acts like a perk)**
- [ ] Recoil Reduction (Invisible Grip) **(A grip that is not visible but still gives the same stat changes as a grip: for cosmetic purposes -- acts like a perk)**
- [ ] Recoil Reduction (Invisible Muzzle Break) **(A muzzle break that is not visible but still gives the same stat changes as a muzzle break: for cosmetic purposes -- acts like a perk)**
- [ ] Silenced (Invisible Silencer) **(A silencer that is not visible but still gives the same silenced effect as a silencer: for cosmetic purposes -- acts like a perk)**
- [ ] Futuristic Sight **A sight that is completely unobtrusive. (Basically a glass pane with a dot on it)**

**New Ammo**
- [ ] Micro Bullet (Does not require casings; exclusive to the Kolibri)
- [ ] PKM Heavy Bullet (Uses heavy casings; exclusive to the PKM)

**Notes**

- The update following this one will contain Hobbeswyn's additions if they do not decide to take down their pull request. This is to give them as much time as possible to change their mind if they so please.
- The stocks on the following planned guns will not be removed and made into individual attachments: SCAR-H, PKM, MP7, 
- The planned change to remove "suppression without attachments" for the Val, Vintorez and 9A-91 is to increase customizability in this mod as well as work as a fix to **Issue** #29 
- This list is not final and is constantly changing. There is a lot of work to be done and not all of it is guaranteed to stay the same priority to us.

**Comment by Autovw** [comment]
> Banshee model improvements
> Muzzle Break model improvements
> MAT-49 model improvements
> Mammoth model improvements

Discussed internally, but I guess we'll make the final decision later.

>  Glock 18 iron sight improvements
 > G11 iron sight improvements
 > AKS-74U iron sight improvements

I think we're all fine with that.

> Several guns with pre-attached stocks have their stocks removed and made into attachments; stock option will become more readily available to the guns in this mod including pistols

We should definitely keep some pre-attached because I don't think flooding the creative tab with stocks is a good idea, but I like the idea of making them more customizable.

> Holo Scope renamed to Tactical Short Scope and made dyeable

We can consider the latter, but I'd rather not rename the item.

> Zerkalo Scope repositioned and made dyeable

The fact it's not dyeable makes this one more unique to me actually.

> Basic Stock renamed to Minimal Stock

This seems rather pointless to me considering the trouble that comes with renames.

> Angled Grip renamed to Commando Grip (It is literally a Call of Duty commando grip)

Same with this one, we don't have to do what CoD does unless it doesn't make sense it all to keep the current name.

> FN2000 renamed to F2000 and made dyeable

We'll keep the file name the same, but we'll just change the name in the translation file. The author didn't like the idea of the gun being dyeable at the time, so that would be a no for now.

> AK-74M renamed to AK-74 Custom
> OTs-03 renamed to SVU

Not sure about these renames. I'd say just keep the original.

> 9A91 renamed to 9A-91

It has always been the 9A-91 in-game. You're probably looking at the file name.

> 9A91 Suppressor removed and made an attachment, iron sight improvements

Which option would you prefer? Silenced by default or separate attachment?


Well, that's everything I have for now.
I'm not trying to sound like I dislike everything, but I'd rather point it out before you make the actual changes. :)

**Comment by CasualNoLifer** [comment]
> > Banshee model improvements
> > Muzzle Break model improvements
> > MAT-49 model improvements
> > Mammoth model improvements
> 
> Discussed internally, but I guess we'll make the final decision later.
> 
> > Glock 18 iron sight improvements
> > G11 iron sight improvements
> > AKS-74U iron sight improvements
> 
> I think we're all fine with that.
> 
> > Several guns with pre-attached stocks have their stocks removed and made into attachments; stock option will become more readily available to the guns in this mod including pistols
> 
> We should definitely keep some pre-attached because I don't think flooding the creative tab with stocks is a good idea, but I like the idea of making them more customizable.
> 
> > Holo Scope renamed to Tactical Short Scope and made dyeable
> 
> We can consider the latter, but I'd rather not rename the item.
> 
> > Zerkalo Scope repositioned and made dyeable
> 
> The fact it's not dyeable makes this one more unique to me actually.
> 
> > Basic Stock renamed to Minimal Stock
> 
> This seems rather pointless to me considering the trouble that comes with renames.
> 
> > Angled Grip renamed to Commando Grip (It is literally a Call of Duty commando grip)
> 
> Same with this one, we don't have to do what CoD does unless it doesn't make sense it all to keep the current name.
> 
> > FN2000 renamed to F2000 and made dyeable
> 
> We'll keep the file name the same, but we'll just change the name in the translation file. The author didn't like the idea of the gun being dyeable at the time, so that would be a no for now.
> 
> > AK-74M renamed to AK-74 Custom
> > OTs-03 renamed to SVU
> 
> Not sure about these renames. I'd say just keep the original.
> 
> > 9A91 renamed to 9A-91
> 
> It has always been the 9A-91 in-game. You're probably looking at the file name.
> 
> > 9A91 Suppressor removed and made an attachment, iron sight improvements
> 
> Which option would you prefer? Silenced by default or separate attachment?
> 
> Well, that's everything I have for now. I'm not trying to sound like I dislike everything, but I'd rather point it out before you make the actual changes. :)

Response to these:

- Gun Model Improvements: I have improved several models and they were accepted. This idea is to improve upon the four current least popular models in the mod. They would not be completely remodeled and their original concepts would be retained.

- Iron sight improvements: 👍 

- Regarding making built-in stocks attachments: Not sure what you mean by flooding. There would be 4 stocks as a result of this change: 
1. AKM Custom and AK-74m both have the same stock and it would become an attachment.
2. The M16A2 stock would become an attachment
3. The AK-12 and AK-15 have the same stock and it would become an attachment.
4. The M4A4 and M4A1-s have the same stock and it would become an attachment.

- Holo Scope: The changes I suggested were supposed to be tied into the F2000. The current color of the Holo Scope perfectly matches the color of the F2000. I would only suggest recoloring it if the F2000 was able to be dyed. As for the name, the name change was suggested because the sight is not a holographic sight. If there is a way to change the sight picture for the Holo Scope, that would fix the issue.

- Zerkalo Scope: This change was suggested because the color scheme doesn't match anything. It definitely does need to be repositioned because the dot is not centered and the sight clips into most models where other sights do not. It would retain its texture but just be dyeable.

- Does renaming an item really take that much effort? I don't mean changing the item ID. I just mean changing the name of the item IN GAME.

- AK-74m being called what it is doesn't make much sense to me when there's the AKM Custom. the m after AK-74 means "modular" which can be considered a synonym of "Custom" in this case. I think they should have the same identification as a modular version of their respective weapons: e.g., they're either AK-74m and AKMm or AK-74 Custom and AKM Custom.

- The OTs-03 being renamed to the SVU is understandable. I would suggest making it "Dragunov" or "Dragunov SVU" instead. The Dragunov SVU is the "real" name of the weapon and would make the weapon more popular. To be clear, the OTs-03 and the Dragunov SVU are the same gun - it would be renaming to clarify what the gun is and increase it's popularity

- Basic stock and angled grip renames 👍 

- 9A-91: wasn't aware that that was the in-game name, my bad. As for the silencer situation, the gun actually looks ridiculous without it and I thought having a funny gun might be nice, haha. It would not be silenced by default but have the silencer option. I was considering suggesting doing this for the VAL and Vintorez since they both have IRL barrel counterparts that are not silenced, and making their silencers attachments as well. This would further increase the customization in the mod.

**Comment by Autovw** [comment]
> There would be 4 stocks as a result of this change

Say no more, I'm in.

> Holo Scope: *[...]* As for the name, the name change was suggested because the sight is not a holographic sight. If there is a way to change the sight picture for the Holo Scope, that would fix the issue.

If someone makes a new picture, sure.

> Zerkalo Scope: This change was suggested because the color scheme doesn't match anything. It definitely does need to be repositioned because the dot is not centered and the sight clips into most models where other sights do not. It would retain its texture but just be dyeable.

I guess I'll just wait to see the end result.

> Does renaming an item really take that much effort? I don't mean changing the item ID. I just mean changing the name of the item IN GAME.

Changing the item ID is the scary part for sure. Changing the translation name would be okay, but if it's something *completely* different from the item ID people will be confused.

> AK-74m being called what it is doesn't make much sense to me when there's the AKM Custom. the m after AK-74 means "modular" which can be considered a synonym of "Custom" in this case. I think they should have the same identification as a modular version of their respective weapons: e.g., they're either AK-74m and AKMm or AK-74 Custom and AKM Custom.

I guess, I'll have to think about it.

> The OTs-03 being renamed to the SVU is understandable. I would suggest making it "Dragunov" or "Dragunov SVU" instead. The Dragunov SVU is the "real" name of the weapon and would make the weapon more popular. To be clear, the OTs-03 and the Dragunov SVU are the same gun - it would be renaming to clarify what the gun is and increase it's popularity

Same for this one.

> 9A-91: wasn't aware that that was the in-game name, my bad. As for the silencer situation, the gun actually looks ridiculous without it and I thought having a funny gun might be nice, haha. It would not be silenced by default but have the silencer option. I was considering suggesting doing this for the VAL and Vintorez since they both have IRL barrel counterparts that are not silenced, and making their silencers attachments as well. This would further increase the customization in the mod.

I'll leave this one up to you for now :)
